# Generated by Django 5.1.4 on 2025-01-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='')),
                ('dept', models.CharField(max_length=50, verbose_name='')),
                ('batch', models.IntegerField(verbose_name='')),
                ('number', models.CharField(max_length=50, verbose_name='')),
                ('message', models.TextField(verbose_name='')),
                ('allotedHall', models.CharField(max_length=50, verbose_name='')),
                ('desiredHall', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
    ]
