# Generated by Django 5.1.4 on 2025-01-18 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='allotedHall',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='desiredHall',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(max_length=50),
        ),
    ]
