# Generated by Django 5.2 on 2025-07-07 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_student_roll_alter_student_allotedhall_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('batch', 'roll')},
        ),
    ]
